// lib/mockData.ts
import { Project } from "@/types/workspace";

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Project Alpha",
    owner_id: "user1",
    parent_id: null,
    description: "Main project",
    status: "active",
    visibility: "private",
    metadata: {},
    icon: "📁",
    cover_image: null,
    children: [
      {
        id: "2",
        name: "Project A",
        owner_id: "user1",
        parent_id: "1",
        description: "Project A description",
        status: "active",
        visibility: "private",
        metadata: {},
        icon: "📁",
        cover_image: null,
        children: [],
        documents: [],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "3",
        name: "Resources",
        owner_id: "user1",
        parent_id: "1",
        description: "Project resources",
        status: "active",
        visibility: "private",
        metadata: {},
        icon: "📚",
        cover_image: null,
        children: [
          {
            id: "4",
            name: "Images",
            owner_id: "user1",
            parent_id: "3",
            description: "Project images",
            status: "active",
            visibility: "private",
            metadata: {},
            icon: "🖼️",
            cover_image: null,
            children: [],
            documents: [],
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
          },
        ],
        documents: [],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
    documents: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
